version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./backend/docker-setup/mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern_docker_starter
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

networks:
  default:
    name: mern-docker-network
